name: Sync Repo
on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  bluez:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bluez/action-sync-repo@master
      with:
        src_repo: 'https://git.kernel.org/pub/scm/bluetooth/bluez.git'
        src_branch: 'master'
        dest_repo: 'bluez/bluez'
        dest_branch: 'master'
        secret_token: ${{ secrets.ACTION_TOKEN }}
